const urlIdMapping = `:104
residence-etudiante-vol-de-nuit-rennes:74
univercity-residence-etudiante-chambery:25
renon-residence-etudiante-vincennes:66
residence-etudiante-nicolas-copernic-champs-sur-marne:78
jean-francois-deniau-residence-etudiante-noisy-le-sec:53
berthelot-residence-chercheurs-meudon:39
infanti-residence-etudiante-oullins:54
bernard-barataud-residence-etudiante-evry-courcouronnes:26
cite-de-la-musique-residence-etudiante-paris:67
pierre-gilles-de-gennes-residence-etudiante-villejuif:68
simone-veil-residence-etudiante-neuilly-plaisance:76
residence-etudiante-george-sand-saint-denis:77
du-conservatoire-residence-etudiante-paris:69
camille-see-residence-etudiante-saint-denis:60
residence-etudiante-suresnes:102
etudiant-cergy:89
residence-etudiante-marseille-10eme:101
saint-ouen:100
etudiante-le-tandem-metz:87
etudiante-henri-krasucki-noisiel:88
omega-residence-etudiante-aubervilliers:2
carmen-caron-residence-jeunes-actifs-aubervilliers:1
ariane-residence-etudiante-meylan:4
les-bords-de-seine-residence-etudiante-alfortville:3
carmen-caron-residence-etudiante-aubervilliers:6
residence-etudiante-henri-langlois-bois-darcy:7
alpha-residence-etudiante-aubervilliers:5
residence-liberte:9
pierre-bourdieu-residence-etudiante-bonneuil-sur-marne:10
etudiant-bezons:90
recouvrance-residence-etudiante-brest:11
saint-luc-residence-etudiante-brest:8
louis-faure-dujarric-residence-jeunes-actifs-colombes:15
volti-residence-etudiante-cachan:16
jean-zay-residence-jeunes-actifs-cesson:14
terre-des-hommes-residence-etudiante-bruz:13
residence-etudiante-paul-delouvrier-cergy-pontoise:18
du-technopole-residence-etudiante-brest:12
du-parc-residence-etudiante-charenton-le-pont:22
les-choux-de-creteil-residence-etudiante:24
residence-etudiante-ampere-champs-sur-marne:21
residence-etudiante-meunier-champs-sur-marne:20
perronet-residence-etudiante-champs-sur-marne:19
jean-zayresidence-etudiante-cesson:23
la-cerisaie-residence-jeunes-actifs-fresnes:28
residence-etudiante-andre-dunoyer-segonzac-guyancourt:32
epigone-residence-etudiante-grenoble:31
residence-etudiante-larose-gennevilliers:30
saint-exupery-residence-jeunes-actifs-evry-courcouronnes:27
residence-etudiante-baudin-gennevilliers:29
jazz-residence-jeunes-actifs-mantes-la-ville:36
wangari-maathai-residence-jeunes-actifs-montreuil:35
jean-paul-goude-residence-etudiante-saint-mande:38
nicolas-appert-residence-etudiante-ivry-sur-seine:33
porte-ditalie-residence-etudiante-le-kremlin-bicetre:34
eugene-chevreul-residence-etudiante-massy:37
jazz-residence-etudiante-mantes-la-ville:40
le-rodrigue-residence-etudiante-montreuil:42
frida-kahlo-residence-etudiante-montreuil:41
residence-etudiante-adele-andre-lambert-maurepas:43
residence-etudiante-la-fayette-technopole-metz:45
wangari-maathai-residence-etudiante-montreuil:44
michel-serres-le-luzard-partie-pour-jeunes-actifs:46
chanzy-residence-etudiante-nanterre:48
neuilly-roule-residence-etudiante-neuilly-sur-seine:52
andre-devambez-residence-etudiante-neuilly-plaisance:49
michel-serres-le-luzard-residence-etudiante-noisiel:51
pierre-gilles-de-gennes-residence-etudiante-noisiel:50
alfred-sisley-residence-etudiante-le-port-marly:56
edgar-faure-residence-etudiante-palaiseau:55
alexandre-manceau-residence-etudiante-palaiseau:59
les-bruyeres-residence-etudiante-rennes:57
alexandre-manceau-residence-jeunes-actifs-palaiseau:58
campuseo-residence-jeunes-actifs-velizy-villacoublay:62
millenium-residence-jeunes-actifs-velizy-villacoublay:61
philippe-auguste-residence-jeunes-actifs-vincennes:63
campuseo-partie-pour-etudiants-residence-etudiante-velizy-villacoublay:65
residence-jeunes-actifs-la-cybele-voisins-le-bretonneux:64
residence-etudiante-la-cybele-voisins-le-bretonneux:70
millenium-residence-etudiante-velizy-villacoublay:72
jacques-henri-lartigue-residence-etudiante-courbevoie:75
val-pompadour-residence-etudiante-valenton:71
victor-guerreau-residence-etudiante-velizy-villacoublay:73
residence-etudiante-palet-cergy:80
residence-etudiante-georges-melies-montreuil:79
residence-etudiante-alfred-sisley-extension-port-marly:84
residence-etudiante-internat-valerieux-chambery:81
residence-etudiante-rosa-parks-eaubonne:83
etudiante-pierre-vidal-naquet-saint-denis:85
etudiante-eole-paris:86
residence-etudiante-george-sand-eaubonne:82
etudiante-vivaldi-villeneuve-dascq:94
la-garenne-colombes:91
pierrefitte-sur-seine:98
etudiante-suresnes:93
saint-mande-2:106
aubert-residence-etudiante-vincennes:103
saint-mande:105
residence-etudiante-poseidon-cergy-pontoise:17`;

module.exports = urlIdMapping;
